### ISSUE TITLE
Error compiling for Generic ESP8266

### ISSUE THREAD

**Issue by Mustafa-MS** [cristiansteib/GPS-neo-6m#3]
Hello,

There is a problem when compiling this library for generic ESP8266.
this is the error code

```
Arduino: 1.8.2 (Windows 7), Board: "Generic ESP8266 Module, 80 MHz, 40MHz, DIO, 115200, 512K (64K SPIFFS), ck, Disabled, None"

Build options changed, rebuilding all
C:\Users\Bike\Documents\Arduino\ECP7_GPSNeo\ECP7_GPSNeo.ino:3:28: fatal error: avr/pgmspace.h: No such file or directory

#include <avr/pgmspace.h>

^

compilation terminated.

exit status 1
Error compiling for board Generic ESP8266 Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

**Comment by Mustafa-MS** [comment]
I managed to solve this problem by changing 
#include <avr/pgmspace.h> in Gpsneo.cpp, to the following 
` #if defined ( ESP8266 )
  #include <pgmspace.h>
#else
  #include <avr/pgmspace.h>
#endif `

Thanks for your great work.

**Comment by JanashreeA** [comment]
@Mustafa-MS  does this library work fine with esp8266 
I am a newbie, so could you share me the hook up connection between nodemcu and gps module
