### ISSUE TITLE
problem with generic esp8266

### ISSUE THREAD

**Issue by JanashreeA** [cristiansteib/GPS-neo-6m#6]
C:\Program Files (x86)\Arduino\libraries\GPS-neo-6m\Gpsneo.cpp:4:27: fatal error: avr/pgmspace.h: No such file or directory

 #include <avr/pgmspace.h> 

                           ^

compilation terminated.

Multiple libraries were found for "SoftwareSerial.h"
 Used: C:\Users\ANAND\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0\libraries\SoftwareSerial
 Not used: C:\Program Files (x86)\Arduino\libraries\SoftwareSerial
Using library SoftwareSerial at version 1.0 in folder: C:\Users\ANAND\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0\libraries\SoftwareSerial 
Using library GPS-neo-6m in folder: C:\Program Files (x86)\Arduino\libraries\GPS-neo-6m (legacy)
exit status 1
Error compiling for board Generic ESP8266 Module.

plz to help me to sort it out
Thanks in advance

**Comment by per1234** [comment]
Why did you open a duplicate issue when you [already saw](https://github.com/cristiansteib/GPS-neo-6m/issues/3#issuecomment-369466212) the original one and the solution two hours earlier?

GitHub issue trackers are a place to report bugs, not ask to have your hand held. The appropriate place to ask for help is the [Arduino Forum](http://forum.arduino.cc/).
